os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - develop
    - master

before_script:
  - env | sort
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`

script:
  # Test containers build
  - travis_retry docker-compose build
  # Test containers run
  - docker-compose up -d && sleep 240
  - docker-compose ps
  #- docker-compose logs
  - docker-compose logs "taiga_back"
  - docker-compose ps "taiga_back" | grep "Up"
  - docker-compose logs "taiga_celery"
  - docker-compose ps "taiga_celery" | grep "Up"
  # Test containers can be dropped and restarted
  - docker-compose down
  - docker-compose up -d && sleep 240
  - docker-compose ps
  #- docker-compose logs
  - docker-compose logs "taiga_back"
  - docker-compose ps "taiga_back" | grep "Up"
  - docker-compose logs "taiga_celery"
  - docker-compose ps "taiga_celery" | grep "Up"

after_script:
  - docker images
  - docker ps -a

notifications:
  email: false

env: # Environments
    - VERSION=4.2 VARIANT=alpine
    - VERSION=5.0 VARIANT=alpine
    - VERSION=5.5 VARIANT=alpine
    - VERSION=6.0 VARIANT=alpine
